version: '3.9'

services:
    db:
      image: postgres:latest
      env_file: .env
      ports:
          - 5432:5432

    migration: 
        build: .
        env_file: .env 
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn typeorm migration:run -d src/data-source.ts'
        volumes: 
            - .:/app
        depends_on: 
            - db

    web:
        build: . 
        env_file: .env 
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
        volumes: 
            - .:/app
        ports: 
            - 3000:3000

        depends_on: 
            - db
            - migration

volumes: 
    pgdata: